version: '3.8'

services:
  localdb:
    image: "mysql:8.0.34-debian"
    platform: ${MYSQL_LOCAL_PLATFORM}
    container_name: mysql-local
    environment:
      MYSQL_DATABASE: ${MYSQL_LOCAL_DATABASE}
      MYSQL_USER: ${MYSQL_LOCAL_USER}
      MYSQL_PASSWORD: ${MYSQL_LOCAL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_LOCAL_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    volumes:
      - shared-data:/app/mysql-local
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    restart: always

volumes:
  shared-data:
