version: '3.8'

services:
  app:
    container_name: second-hand-app
    image: roadj/second-hand-app:latest
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    volumes:
      - shared-data:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  shared-data:
